### Numpy is the numerical computing package in Python

In [1]:
import numpy as np

The import statement is used to import external libraries. All functions within the imported library are now accesible through that library's namespace. Since we imported numpy as "np", we can now access the functions within the Numpy library through: np.\<function name\>

In [4]:
np.array( [1, 2, 3, 4] )

array([1, 2, 3, 4])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The arange function takes in the "start" value, "stop" value, and the "step" size as inputs and returns an evenly spaced array. For more information, read the documentation: 

In [8]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [3]:
np.linspace(0, 9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.array([ [1,1], [1,1] ])

array([[1, 1],
       [1, 1]])

In [13]:
arr = np.ones( (2,2) )
arr

array([[1., 1.],
       [1., 1.]])

Above, we created a matrix with 3 rows and 4 columns. It has a shape of 3 x 4

In [14]:
arr.shape

(2, 2)

In [8]:
np.full_like(np.zeros(10), 10)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [16]:
np.ones(10) * 10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [19]:
x = 2 #integer
y = "this is a string"
x * y

'this is a stringthis is a string'

## Why use numpy?

Firstly, numpy provides access to efficient and optimized implementation of array handling operations. For instance, let's repeat the exercise from the previous notebook, where we created a list of 1000 elements and performed certain operations on each element.

In [21]:
%%timeit
x = []
for i in range(0, 1000, 1):
    x.append(i**2 + 0.5 * i + 2.5)

305 µs ± 3.13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
%%timeit 
xn = np.arange(0, 1000, 1)
xn = xn**2 + 0.5 * xn + 2.5

8.98 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<br/><br/>
Numpy is ~2 orders of magnitude faster!

The pure Python way of doing things is slower because Python is a dynamically typed language and the compiler may not implement memory optimizations such as loading up the array elements into memory before the operation is carried out.

But the numpy way of doing things is faster because the underlying code is written in C, and we get all the optimization that comes with having defined types and compiler optimizations with memory management. We also avoid the overheads that come with storing the data type and checking it before every operation is carried out, leading to much faster running code!

### Indexing in numpy

In [25]:
x = np.arange(5, 10, 1)

In [26]:
x

array([5, 6, 7, 8, 9])

In [28]:
x.shape

(5,)

In [27]:
print(x[0], x[1], x[2], x[3], x[4])

5 6 7 8 9


In [29]:
print(x[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

#### Index 5 threw an error because our array has elements in the 0th, 1st, 2nd, 3rd, and 4th positions only. Remember, indexing in Python begins from 0

In [38]:
print(x[0: 5])

[5 6 7 8 9]


In [33]:
print(x[-1], x[-2], x[-3], x[-4], x[-5])

9 8 7 6 5


Numpy slicing opperator is ":" the colon. Use the operator with the lower index and the higher index to access slices of the array

In [32]:
x[0:3]

array([5, 6, 7])

In [39]:
x[::-1]

array([9, 8, 7, 6, 5])

In [40]:
x[::-1]

array([9, 8, 7, 6, 5])

### Array operations

All operations on the numpy object are by default applied to every element in the array

In [41]:
x

array([5, 6, 7, 8, 9])

In [42]:
x + 10

array([15, 16, 17, 18, 19])

In [45]:
x

array([1.5, 1.6, 1.7, 1.8, 1.9])

In [44]:
x = (x + 10) / 10

In [51]:
x

array([ 7.5,  1.6,  1.7, 37.5,  1.9])

In [49]:
x[3] = x[0] * 5

In [50]:
x

array([ 7.5,  1.6,  1.7, 37.5,  1.9])

### Exercise 03: Using both arange and linspace

1. Create an array of length 5, 10, 100, 1000 of equally spaced numbers between 0 and 1 
1. Create a 2 dimensional array, "arr", of shape 3x3, with the first row having all 1's, second row having all 2's, and the third row having all 3's
1. Access the diagonal elements of "arr" created above and multiply it by 10
1. Access the first column of "arr" and add it with the third column of "arr"

In [93]:
arr = np.ones((3,3))

In [77]:
arr[0, 0] = 200

In [84]:
x = np.arange(10)

In [86]:
x[ [0, 1, 2, 3] ]

array([0, 1, 2, 3])

In [90]:
arr[ [0,1] , : ]

array([[200.,   1.,   1.],
       [  1.,   1.,   1.]])

In [88]:
arr

array([[200.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [94]:
arr[1, :] = arr[1, :] * 2
arr[2, :] = arr[2, :] * 3

In [97]:
x

1

In [65]:
arr[ [0,1,2], [0, 1, 2] ]

array([1., 2., 3.])

In [96]:
x = 1